double dist = 0;
int seconds = 0;
double num2;
double x = 0, y = 0;
char arr[] = { 'D','i','s','t','a','n','c','e',':','\0' };
char* tempit;
char xpos[20];
char ypos[20];
double xstart = 0, ystart = 0;
int first = 1;
int num;
double tempdist = 0;
double xtar, ytar;
double latnew, longnew;
double xstart, ystart;
double theta;
double convert;